# -*- coding: utf-8 -*-
"""text_to_speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JeS4AdcIgkSJwmLomPQ4FOhDKKSXzJV2
"""

pip install gTTS

import os;

from gtts import gTTS;

text = input("Enter a text to convert: ");

open_file = open("sample_text.txt");

text_file = open_file.read();

language = 'en';

obj = gTTS(text = text_file, lang = language, slow = False);

obj.save("sample_speech.mp3");

os.system("sample_speech.mp3");